/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.1.3-14-g330caae0c1-20261006"
#endif /* AVUTIL_FFVERSION_H */
