// https://dom.spec.whatwg.org/#interface-documentfragment

[UnimplementedConstructor,
 Exposed=Window]
interface DocumentFragment : Node {
};

DocumentFragment implements NonElementParentNode;
DocumentFragment implements ParentNode;