// https://dom.spec.whatwg.org/#interface-documentfragment

[UnimplementedConstructor,
 Constructor,
 Exposed=Window]
interface DocumentFragment : Node {
  // TODO Support Implements
  // DocumentFragment Implements NonElementParentNode
  // https://www.w3.org/TR/dom/#interface-nonelementparentnode
  [Unimplemented] Element? getElementById(DOMString elementId);


  // TODO Support Implements
  // DocumentFragment Implements ParentNode
  // https://www.w3.org/TR/dom/#parentnode  
  [Unimplemented, SameObject] readonly attribute HTMLCollection children;
  [Unimplemented] readonly attribute Element? firstElementChild;
  [Unimplemented] readonly attribute Element? lastElementChild;
  [Unimplemented] readonly attribute unsigned long childElementCount;

  [Unimplemented] Element? querySelector(DOMString selectors);
  [Unimplemented, NewObject] NodeList querySelectorAll(DOMString selectors);
};

// TODO Support Implements
DocumentFragment implements NonElementParentNode;
DocumentFragment implements ParentNode;