// https://w3c.github.io/DOM-Parsing/#the-domparser-interface

enum SupportedType {
  "text/html",
  "text/xml",
  "application/xml",
  "application/xhtml+xml",
  "image/svg+xml"
};

[
  STARFISH_ENABLE_DOMPARSER,
  Constructor,
  ConstructorCallWith=Starfish
] interface DOMParser {
  [RaisesException, NewObject] Document parseFromString(DOMString str, SupportedType type);
};
