// https://html.spec.whatwg.org/multipage/webappapis.html#globaleventhandlers
[PartialInterface,
NoInterfaceObject]
interface GlobalEventHandlers {
  [Unimplemented] attribute EventHandler onabort;
  [Unimplemented] attribute EventHandler onauxclick;
  [Unimplemented] attribute EventHandler onblur;
  [Unimplemented] attribute EventHandler oncancel;
  [Unimplemented] attribute EventHandler oncanplay;
  [Unimplemented] attribute EventHandler oncanplaythrough;
  [Unimplemented] attribute EventHandler onchange;
  attribute EventHandler onclick;
  [Unimplemented] attribute EventHandler onclose;
  [Unimplemented] attribute EventHandler oncontextmenu;
  [Unimplemented] attribute EventHandler oncuechange;
  [Unimplemented] attribute EventHandler ondblclick;
  [Unimplemented] attribute EventHandler ondrag;
  [Unimplemented] attribute EventHandler ondragend;
  [Unimplemented] attribute EventHandler ondragenter;
  [Unimplemented] attribute EventHandler ondragexit;
  [Unimplemented] attribute EventHandler ondragleave;
  [Unimplemented] attribute EventHandler ondragover;
  [Unimplemented] attribute EventHandler ondragstart;
  [Unimplemented] attribute EventHandler ondrop;
  [Unimplemented] attribute EventHandler ondurationchange;
  [Unimplemented] attribute EventHandler onemptied;
  [Unimplemented] attribute EventHandler onended;
  [Unimplemented] attribute OnErrorEventHandler onerror;
  attribute EventHandler onfocus;
  [Unimplemented] attribute EventHandler oninput;
  [Unimplemented] attribute EventHandler oninvalid;
  attribute EventHandler onkeydown;
  [Unimplemented] attribute EventHandler onkeypress;
  [Unimplemented] attribute EventHandler onkeyup;
  [Unimplemented] attribute EventHandler onload;
  [Unimplemented] attribute EventHandler onloadeddata;
  [Unimplemented] attribute EventHandler onloadedmetadata;
  [Unimplemented] attribute EventHandler onloadend;
  [Unimplemented] attribute EventHandler onloadstart;
  [Unimplemented] attribute EventHandler onmousedown;
  [Unimplemented, LenientThis] attribute EventHandler onmouseenter;
  [Unimplemented, LenientThis] attribute EventHandler onmouseleave;
  [Unimplemented] attribute EventHandler onmousemove;
  [Unimplemented] attribute EventHandler onmouseout;
  attribute EventHandler onmouseover;
  [Unimplemented] attribute EventHandler onmouseup;
  [Unimplemented] attribute EventHandler onwheel;
  [Unimplemented] attribute EventHandler onpause;
  [Unimplemented] attribute EventHandler onplay;
  [Unimplemented] attribute EventHandler onplaying;
  [Unimplemented] attribute EventHandler onprogress;
  [Unimplemented] attribute EventHandler onratechange;
  [Unimplemented] attribute EventHandler onreset;
  [Unimplemented] attribute EventHandler onresize;
  [Unimplemented] attribute EventHandler onscroll;
  [Unimplemented] attribute EventHandler onseeked;
  [Unimplemented] attribute EventHandler onseeking;
  [Unimplemented] attribute EventHandler onselect;
  [Unimplemented] attribute EventHandler onshow;
  [Unimplemented] attribute EventHandler onstalled;
  [Unimplemented] attribute EventHandler onsubmit;
  [Unimplemented] attribute EventHandler onsuspend;
  [Unimplemented] attribute EventHandler ontimeupdate;
  [Unimplemented] attribute EventHandler ontoggle;
  [Unimplemented] attribute EventHandler onvolumechange;
  [Unimplemented] attribute EventHandler onwaiting;
};