// https://dom.spec.whatwg.org/#htmlcollection
// NOTE Using NotEnumerable at getter instead of LegacyUnenumerableNamedProperties at interface

[Exposed=Window]
interface HTMLCollection {
  readonly attribute unsigned long length;
  getter Element? item(unsigned long index);
  [NotEnumerable] getter Element? namedItem(DOMString name);
};