// https://w3c.github.io/media-source/#sourcebufferlist

[STARFISH_ENABLE_MULTIMEDIA]
interface SourceBufferList : EventTarget {
  readonly attribute unsigned long length;
  [Unimplemented] attribute EventHandler onaddsourcebuffer;
  [Unimplemented] attribute EventHandler onremovesourcebuffer;
  getter SourceBuffer (unsigned long index);
};