// https://html.spec.whatwg.org/multipage/embedded-content.html#time-ranges

[STARFISH_ENABLE_MULTIMEDIA]
interface TimeRanges {
  readonly attribute unsigned long length;
  double start(unsigned long index);
  double end(unsigned long index);
};