// https://www.w3.org/TR/touch-events/#touchevent-interface

interface TouchEvent : UIEvent {
  [Unimplemented] readonly attribute TouchList touches;
  [Unimplemented] readonly attribute TouchList targetTouches;
  [Unimplemented] readonly attribute TouchList changedTouches;
  [Unimplemented] readonly attribute boolean altKey;
  [Unimplemented] readonly attribute boolean metaKey;
  [Unimplemented] readonly attribute boolean ctrlKey;
  [Unimplemented] readonly attribute boolean shiftKey;
};