// https://url.spec.whatwg.org/#url
// NOTE Using DOMString instead of USVString

[Constructor(DOMString url, optional DOMString base),
 Exposed=(Window,Worker)]
interface URL {
  [STARFISH_ENABLE_TEST] stringifier attribute DOMString href;
  [STARFISH_ENABLE_TEST] readonly attribute DOMString origin;
  [STARFISH_ENABLE_TEST] attribute DOMString protocol;
  [STARFISH_ENABLE_TEST] attribute DOMString username;
  [STARFISH_ENABLE_TEST] attribute DOMString password;
  [STARFISH_ENABLE_TEST] attribute DOMString host;
  [STARFISH_ENABLE_TEST] attribute DOMString hostname;
  [STARFISH_ENABLE_TEST] attribute DOMString port;
  [STARFISH_ENABLE_TEST] attribute DOMString pathname;
  [STARFISH_ENABLE_TEST] attribute DOMString search;
  [Unimplemented, SameObject] readonly attribute URLSearchParams searchParams;
  [STARFISH_ENABLE_TEST] attribute DOMString hash;
  [Unimplemented] DOMString toJSON();


  // partial
  // https://w3c.github.io/FileAPI/#creating-revoking
  static DOMString createObjectURL(Blob blob);
  static void revokeObjectURL(DOMString url);
};