/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

#include "MP4.TFHD.h"

using namespace MP4;
          
TFHD::TFHD( void )
{
}

void TFHD::processData( MP4::BinaryStream * stream, size_t length )
{
    uint8_t v = stream->readUnsignedChar();
    uint32_t f = (stream->readUnsignedChar() << 16) + (stream->readUnsignedChar() << 8) + (stream->readUnsignedChar() << 0);

    track_id = stream->readBigEndianUnsignedInteger();

    if (f & 0x01) {
        // Base data offset
        stream->readBigEndianUnsignedLong();
    }
    if (f & 0x02) {
        // Base data offset
        stream->readBigEndianUnsignedInteger();
    }
    if (f & 0x08) {
        default_sample_duration = stream->readBigEndianUnsignedInteger();
        has_default_sample_duration = true;
    } else {
        has_default_sample_duration = false;
    }
    if (f & 0x10) {
        // default sample size
        default_sample_size = stream->readBigEndianUnsignedInteger();
        has_default_sample_size = true;
    } else {
        has_default_sample_size = false;
    }

    if (f & 0x20) {
        // Default Sample Flags
        default_sample_flags = stream->readBigEndianUnsignedInteger();
        has_default_sample_flags = true;
    } else {
        has_default_sample_flags = false;
    }
    /*
    if (f & 0x10000) {
        boxContent['Duration-is-empty'] = true;
    }
    if (f & 0x20000) {
        boxContent['Default-base-is-moof'] = true;
    }*/
}
