/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

#include "MP4.Parser.h"
#include "atoms.h"
#include "stdio.h"
#include "string.h"

using namespace MP4;

ParserException::ParserException( void )
{
    this->code = -1;
}

ParserException::ParserException( unsigned int c )
{
    this->code = c;
}

const char * ParserException::what( void ) const throw()
{
    switch( this->code )
    {
        case ParserException::NoFileName:
            
            return "No input file";
    }
    
    return "Unknown exception";
}

Parser::Parser( void )
{
    ParserException e = ParserException( ParserException::NoFileName );
    
    throw e;
}

Parser::Parser( char * filename )
{
    bool                 container;
    uint32_t             length;
    uint64_t             dataLength;
    char                 type[ 5 ];
    char               * data;
    MP4::Atom          * atom;
    MP4::ContainerAtom * containerAtom;
    MP4::ContainerAtom * parentAtom;
    
    this->_stream = new BinaryStream( filename );
    this->_file   = new MP4::File();
    data          = NULL;
    atom          = NULL;
    containerAtom = NULL;
    container     = false;
    parentAtom    = this->_file;
    
    memset( type, 0, 5 );
    
    while( !this->_stream->eof() )
    {
        length     = this->_stream->readBigEndianUnsignedInteger();
        dataLength = 0;
        
        this->_stream->read( ( char * )type, 4 );
        
        if( length == 1 )
        {
            dataLength = this->_stream->readBigEndianUnsignedInteger() - 16;
        }
        else
        {
            dataLength = length - 8;
        }
        
        uint32_t typeInt = MP4_PARSER_DEFINE_TYPE_STRING(type);

        Atom* atom = atomFactory(typeInt);

        /* Container atoms */
        if (atom->isContainerAtom())
        {
            containerAtom = (MP4::ContainerAtom*)atom;
            parentAtom->addChild( containerAtom );
            parentAtom = containerAtom;
            continue;
        }
        
        parentAtom->addChild( atom );
        
        ( ( MP4::DataAtom * )atom )->processData( this->_stream, dataLength );
    }
    
}

Parser::~Parser( void )
{
    delete this->_stream;
    delete this->_file;
}

namespace MP4 {

Atom* atomFactory(const uint32_t type)
{
    switch (type) {
        case (MP4_PARSER_DEFINE_TYPE_STRING("dinf")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("edts")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("ipro")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("mdia")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("meta")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("mfra")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("minf")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("moof")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("moov")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("mvex")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("sinf")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("skip")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("stbl")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("traf")):
        case (MP4_PARSER_DEFINE_TYPE_STRING("trak")):
            return new MP4::ContainerAtom( type );
        case (MP4_PARSER_DEFINE_TYPE_STRING("stsd")):
            return new MP4::ContainerAtom( type , 8);
        case (MP4_PARSER_DEFINE_TYPE_STRING("avc1")):
            return new MP4::ContainerAtom( type , 78);
        default:
            break;
    };

    /* Data atoms */
    switch (type) {
    case (MP4_PARSER_DEFINE_TYPE_STRING("avcC")):
        return (new MP4::AVCC());
    case (MP4_PARSER_DEFINE_TYPE_STRING("bxml")):
        return (new MP4::BXML());
    case (MP4_PARSER_DEFINE_TYPE_STRING("co64")):
        return (new MP4::CO64());
    case (MP4_PARSER_DEFINE_TYPE_STRING("cprt")):
        return (new MP4::CPRT());
    case (MP4_PARSER_DEFINE_TYPE_STRING("ctts")):
        return (new MP4::CTTS());
    case (MP4_PARSER_DEFINE_TYPE_STRING("dref")):
        return (new MP4::DREF());
    case (MP4_PARSER_DEFINE_TYPE_STRING("elst")):
        return (new MP4::ELST());
    case (MP4_PARSER_DEFINE_TYPE_STRING("esds")):
        return (new MP4::ESDS());
    case (MP4_PARSER_DEFINE_TYPE_STRING("free")):
        return (new MP4::FREE());
    case (MP4_PARSER_DEFINE_TYPE_STRING("frma")):
        return (new MP4::FRMA());
    case (MP4_PARSER_DEFINE_TYPE_STRING("ftyp")):
        return (new MP4::FTYP());
    case (MP4_PARSER_DEFINE_TYPE_STRING("hdlr")):
        return (new MP4::HDLR());
    case (MP4_PARSER_DEFINE_TYPE_STRING("hmhd")):
        return (new MP4::HMHD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("iinf")):
        return (new MP4::IINF());
    case (MP4_PARSER_DEFINE_TYPE_STRING("iloc")):
        return (new MP4::ILOC());
    case (MP4_PARSER_DEFINE_TYPE_STRING("imif")):
        return (new MP4::IMIF());
    case (MP4_PARSER_DEFINE_TYPE_STRING("ipmc")):
        return (new MP4::IPMC());
    case (MP4_PARSER_DEFINE_TYPE_STRING("mdat")):
        return (new MP4::MDAT());
    case (MP4_PARSER_DEFINE_TYPE_STRING("mdhd")):
        return (new MP4::MDHD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("mehd")):
        return (new MP4::MEHD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("mfhd")):
        return (new MP4::MFHD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("mfro")):
        return (new MP4::MFRO());
    case (MP4_PARSER_DEFINE_TYPE_STRING("mp4a")):
        return (new MP4::MP4A());
    case (MP4_PARSER_DEFINE_TYPE_STRING("mvhd")):
        return (new MP4::MVHD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("padb")):
        return (new MP4::PADB());
    case (MP4_PARSER_DEFINE_TYPE_STRING("pdin")):
        return (new MP4::PDIN());
    case (MP4_PARSER_DEFINE_TYPE_STRING("pitm")):
        return (new MP4::PITM());
    case (MP4_PARSER_DEFINE_TYPE_STRING("sbgp")):
        return (new MP4::SBGP());
    case (MP4_PARSER_DEFINE_TYPE_STRING("schi")):
        return (new MP4::SCHI());
    case (MP4_PARSER_DEFINE_TYPE_STRING("schm")):
        return (new MP4::SCHM());
    case (MP4_PARSER_DEFINE_TYPE_STRING("sdtp")):
        return (new MP4::SDTP());
    case (MP4_PARSER_DEFINE_TYPE_STRING("sgpd")):
        return (new MP4::SGPD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("smhd")):
        return (new MP4::SMHD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("subs")):
        return (new MP4::SUBS());
    case (MP4_PARSER_DEFINE_TYPE_STRING("stsd")):
        return (new MP4::STSD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("stco")):
        return (new MP4::STCO());
    case (MP4_PARSER_DEFINE_TYPE_STRING("stdp")):
        return (new MP4::STDP());
    case (MP4_PARSER_DEFINE_TYPE_STRING("stsc")):
        return (new MP4::STSC());
    case (MP4_PARSER_DEFINE_TYPE_STRING("stsh")):
        return (new MP4::STSH());
    case (MP4_PARSER_DEFINE_TYPE_STRING("stss")):
        return (new MP4::STSS());
    case (MP4_PARSER_DEFINE_TYPE_STRING("stsz")):
        return (new MP4::STSZ());
    case (MP4_PARSER_DEFINE_TYPE_STRING("stts")):
        return (new MP4::STTS());
    case (MP4_PARSER_DEFINE_TYPE_STRING("stz2")):
        return (new MP4::STZ2());
    case (MP4_PARSER_DEFINE_TYPE_STRING("tfdt")):
        return (new MP4::TFDT());
    case (MP4_PARSER_DEFINE_TYPE_STRING("tfhd")):
        return (new MP4::TFHD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("tfra")):
        return (new MP4::TFRA());
    case (MP4_PARSER_DEFINE_TYPE_STRING("tkhd")):
        return (new MP4::TKHD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("tref")):
        return (new MP4::TREF());
    case (MP4_PARSER_DEFINE_TYPE_STRING("trex")):
        return (new MP4::TREX());
    case (MP4_PARSER_DEFINE_TYPE_STRING("trun")):
        return (new MP4::TRUN());
    case (MP4_PARSER_DEFINE_TYPE_STRING("udta")):
        return (new MP4::UDTA());
    case (MP4_PARSER_DEFINE_TYPE_STRING("vmhd")):
        return (new MP4::VMHD());
    case (MP4_PARSER_DEFINE_TYPE_STRING("xml ")):
        return (new MP4::XML());
    };

    return new MP4::UnknownAtom(type);
}

}
