/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

#include "MP4.TRUN.h"

using namespace MP4;
          
TRUN::TRUN( void )
{
}

void TRUN::processData( MP4::BinaryStream * stream, size_t length )
{
    uint8_t v = stream->readUnsignedChar();
    uint32_t f = (stream->readUnsignedChar() << 16) + (stream->readUnsignedChar() << 8) + (stream->readUnsignedChar() << 0);

    has_data_offset = f & 0x0001;
    has_first_sample_flags = f & 0x0004;
    has_sample_duration = f & 0x0100;
    has_sample_size = f & 0x0200;
    has_sample_flags = f & 0x0400;
    has_sample_composition_time_offset = f & 0x0800;

    uint32_t sample_count = stream->readBigEndianUnsignedInteger();
    uint32_t data_offset = 0;
    size_t first_sample_flags = 0;

    if (has_data_offset)
    {
        data_offset = stream->readBigEndianUnsignedInteger();
    }

    if (has_first_sample_flags)
    {
        uint32_t first_sample_flags = stream->readBigEndianUnsignedInteger();
    }

    size_t sample_row_size = (has_sample_duration && 4) + (has_sample_size && 4) + (has_sample_flags && 4) + (has_sample_composition_time_offset && 4);

    size_t t_dur = 0;
    for (size_t k = 0; k < sample_count; ++k)
    {
        Sample sample;

        uint32_t sample_flags = -1;
        uint32_t sample_composition_time_offset = -1;

        if (has_sample_duration) {
            sample.duration = stream->readBigEndianUnsignedInteger();
            t_dur += sample.duration;
        }

        if (has_sample_size) {
            sample.size = stream->readBigEndianUnsignedInteger();
        }

        if (has_sample_flags) {
            sample.flags = stream->readBigEndianUnsignedInteger();
        }

        if (has_sample_composition_time_offset) {
            sample.composition_time_offset = stream->readBigEndianUnsignedInteger();
        }
        samples.push_back(sample);
    }
}
