/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

#include "MP4.AVCC.h"

using namespace MP4;
          
AVCC::AVCC( void )
{
}

void AVCC::processData( MP4::BinaryStream * stream, size_t length )
{
    version = stream->readUnsignedChar();
    profile_ind = stream->readUnsignedChar();
    profile_com = stream->readUnsignedChar();
    level = stream->readUnsignedChar();
    nal_length = (stream->readUnsignedChar() & 0x03) + 1;

    unsigned char tmp1 = stream->readUnsignedChar();
    unsigned char numSps = tmp1 & 0x1f;

    for (size_t i = 0; i < numSps; ++i)
    {
        uint16_t spsSize = stream->readBigEndianUnsignedShort();
        std::vector<uint8_t> sps;
        sps.resize(spsSize);
        stream->read((char*)sps.data(), spsSize);
        spsVector.push_back(std::move(sps));
    }

    unsigned char tmp2 = stream->readUnsignedChar();
    unsigned char numPps = tmp2 & 0x1f;
    for (size_t i = 0; i < numPps; ++i)
    {
        uint16_t ppsSize = stream->readBigEndianUnsignedShort();
        std::vector<uint8_t> pps;
        pps.resize(ppsSize);
        stream->read((char*)pps.data(), ppsSize);
        ppsVector.push_back(std::move(pps));
    }
}
