/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

#include "MP4.ELST.h"

using namespace MP4;
          
ELST::ELST( void )
{
}

void ELST::processData( MP4::BinaryStream * stream, size_t length )
{
	// Version (+8)
	uint8_t v = stream->readUnsignedChar();
	// Flags (+24)
	uint32_t f = (stream->readUnsignedChar() << 16) + (stream->readUnsignedChar() << 8) + (stream->readUnsignedChar() << 0);
	// Size (+32)
	uint32_t entry_count = stream->readBigEndianUnsignedInteger();
    if (v == 1) {
    	for (size_t i = 0; i < entry_count; i++) {
    		// Segment duration (+64)
    		uint64_t segment_duration = stream->readBigEndianUnsignedLong();
    		// Media time (+64)
    		int64_t media_time = stream->readBigEndianUnsignedLong();
    		edit_entries.emplace_back(segment_duration, media_time);
    	}
    } else {
    	// version 0
    	// Segment duration (+32)
    	uint64_t segment_duration = (uint64_t) stream->readBigEndianUnsignedInteger();
    	// Media time (+32)
		int64_t media_time = (int64_t) stream->readBigEndianUnsignedInteger();
		edit_entries.emplace_back(segment_duration, media_time);
    }
    // media_rate_integer (+16)
    stream->readSignedShort();
    // media_rate_fraction (+16)
    stream->readSignedShort();
}
